# Generated by Django 3.2.3 on 2021-05-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='glutenfree',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
    ]
