# Generated by Django 3.2.3 on 2021-05-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='date',
            field=models.CharField(blank=True, help_text='гггг/мм/дд', max_length=100, null=True),
        ),
    ]
