# Generated by Django 3.2.3 on 2021-05-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_sale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='date',
        ),
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.IntegerField(default=0, help_text='скидка в процентах'),
        ),
        migrations.AddField(
            model_name='sale',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog'),
        ),
    ]
