# Generated by Django 3.2.3 on 2021-05-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210524_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vegan',
        ),
    ]
